config/routes.rb
Rails.application.routes.draw do

  root to: 'application#index'

  resources :tasks
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id                :bigint           not null, primary key
#  name              :string
#  description       :text
#  expiration_date   :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :bigint
#  task_status       :integer
#  start_date        :datetime
#  external_event_id :string
#

require "google_calender"

class Task < ApplicationRecord

    belongs_to :user

    before_save :set_default_task_status

    after_create :check_task_status, :delayed_send_gcal_event
    before_destroy :delete_google_calender_event


    enum task_status: [:in_progress, :backlog, :done]

    default_scope { order(created_at: :desc) }


    validates :name, presence: true
    validates :expiration_date, presence: true 
    validates :start_date, presence: true 
  
    validates :start_date, not_in_past: true, on: :create
    validates :expiration_date, not_in_past: true, on: :create
    validate :expiration_date_is_after_start_date
    

    def check_task_status
        current_time = Time.now

        delay.change_task_status(self.id) if current_time > self.expiration_date

        one_day_before = self.expiration_date - 1.days
        one_hour_before = self.expiration_date - 1.hour
        # # Run one day before and one hour
        delay(run_at: one_day_before, attempts: 1).send_reminder(id) if self.expiration_date > current_time && self.task_status == 'in_progress'
        delay(run_at: one_hour_before, attempts: 1).send_reminder(id) if self.expiration_date > current_time && self.task_status == 'in_progress'

        # Change task status after expiration time
        delay(run_at: self.expiration_date + 5.minutes, attempts: 1).send_reminder(self.id) if self.expiration_date > current_time && self.task_status == 'in_progress'

        set_task_status_based_on_dates if current_time > self.expiration_date && self.task_status != 'done'
        true
    end
    
    def set_task_status_based_on_dates
        self.task_status = :backlog if expiration_date < Time.now
        self.task_status = :in_progress if task_status.nil?
    end
    
    def change_task_status(id)
        task = Task.find(id)
        task.set_task_status_based_on_dates
        task.save!
        task
    end

    def send_reminder(id)
        task = Task.find(id)
        UserNotifierMailer.delay.send_task_reminder(task)
    end

    def insert_event_to_google_calender(id)
      task = Task.find(id)
      google_api_client = GoogleCalender.new(task.user, task)
      event = google_api_client.insert_event
      task.external_event_id = event.id
      task.save
      true
    end

    def delayed_send_gcal_event
      delay(attempts: 1).insert_event_to_google_calender(id) if self.is_gcal_linked
      true
    end

    def delete_google_calender_event
      google_api_client = GoogleCalender.new(self.user, self)
      google_api_client.delete_event
      true
    end


    def set_default_task_status
      if task_status.nil?
        self.task_status = :in_progress
      end
    end

    private

    def expiration_date_is_after_start_date
      return if expiration_date.blank? || start_date.blank?
      if expiration_date < start_date
        errors.add(:expiration_date, "cannot be before the start date")
      end
    end    

    def is_gcal_linked
      user.access_token.present?
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.where(user: current_user).page(params[:page])
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.where(id: params[:id], user: current_user).first
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :expiration_date, :start_date, :task_status)
    end

  end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-12">
                <%= f.input :name %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
                <%= f.input :description %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
                  <%= f.select(:task_status, Task.task_statuses.keys.map {|status| [status.titleize,status]}, wrapper_html: {class: "col-sm-6"})  %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
                  <%= f.input :start_date, input_html: {'data-provide': 'datetimepicker1'}, class: 'form-control datetimepicker-input', label: "Start Date", placeholder: "Task End Date" %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <%= f.input :expiration_date, input_html: {'data-provide': 'datetimepicker1'}, class: 'form-control datetimepicker-input', label: "End Date", placeholder: "Task End Date" %>
            </div>
          </div>


        </div>
      </div>
    </div>

    <div class="col-sm-12">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Editing Task</h1>
            <%= render 'form', task: @task %>
            <br/>
            <%= link_to 'Show', @task, class: "btn btn-primary" %> | <%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col">
      <h3>Tasks</h3>
    </div>
    <div class="col">
      <%= link_to "New", new_task_path %>
    </div>
  </div>
  <% @tasks.each do |task| %>
    <div class="row task-wrapper">
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-12">
            <div class="task">
                <div>
                  <p>
                    <strong>Title</strong>: <%= task.name.titleize %>
                  </p>
                </div>
                <div>
                  <% unless task.task_status.nil? %>
                    <p>
                      <strong>Status</strong>: <%= task.task_status.titleize %>
                    </p>
                  <% end %>
                </div>
                <div>
                  <p>
                    <%= link_to "Update", edit_task_path(task) %>|
                    <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </p>
                </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="task">
                <div>
                  <p>
                    <strong>Start Date:</strong> <%= task.start_date %>
                  </p>
                </div>
                <div>
                  <p>
                    <strong>End Date:</strong> <%= task.expiration_date %>
                  </p>
                </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  <% end %>
  <br />
  <div class="row">
    <div class="col-sm-12">
      <%= paginate @tasks %> 
    </div>
  </div>

</div>

app/views/tasks/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>New Task</h1>
            <%= render 'form', task: @task %>
            <br/>
            <%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <p id="notice"><%= notice %></p>
    <%= render 'form', task: @task %>
    <%= link_to 'Edit', edit_task_path(@task) %> |
    <%= link_to 'Back', tasks_path %>

  </div>
</div>